[package]
name = "picotest_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.79", features = ["full"] }
picotest_helpers = { path = "../picotest_helpers" }
rstest = "0.23.0"

[lib]
proc-macro = true
